# Generated by Django 6.0.6 on 2026-06-10 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('course', models.CharField(choices=[('All Courses', 'All Courses'), ('React Full Stack Development', 'React Full Stack Development'), ('Software Development', 'Software Development'), ('Testing', 'Testing'), ('UI/UX Design', 'UI/UX Design'), ('Devops', 'Devops'), ('DevOps', 'DevOps'), ('AI/ML', 'AI/ML'), ('AL/ML', 'AL/ML'), ('Data Science', 'Data Science'), ('Soft Skills', 'Soft Skills')], max_length=100)),
                ('dueDate', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('course_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=50)),
                ('img', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiveClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('targetCourse', models.CharField(choices=[('All Courses', 'All Courses'), ('React Full Stack Development', 'React Full Stack Development'), ('Software Development', 'Software Development'), ('Testing', 'Testing'), ('UI/UX Design', 'UI/UX Design'), ('Devops', 'Devops'), ('DevOps', 'DevOps'), ('AI/ML', 'AI/ML'), ('AL/ML', 'AL/ML'), ('Data Science', 'Data Science'), ('Soft Skills', 'Soft Skills')], max_length=100)),
                ('batchMonth', models.CharField(choices=[('All Batches', 'All Batches'), ('June Batch', 'June Batch'), ('Sept Batch', 'Sept Batch'), ('Dec Batch', 'Dec Batch')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accessType', models.CharField(choices=[('Demo Class (Slot Booking)', 'Demo Class'), ('Full Course (Fully Paid)', 'Full Course')], default='Demo Class (Slot Booking)', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('course', models.CharField(choices=[('All Courses', 'All Courses'), ('React Full Stack Development', 'React Full Stack Development'), ('Software Development', 'Software Development'), ('Testing', 'Testing'), ('UI/UX Design', 'UI/UX Design'), ('Devops', 'Devops'), ('DevOps', 'DevOps'), ('AI/ML', 'AI/ML'), ('AL/ML', 'AL/ML'), ('Data Science', 'Data Science'), ('Soft Skills', 'Soft Skills')], max_length=100)),
                ('fileLink', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecordedClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('videoLink', models.URLField()),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('targetCourse', models.CharField(choices=[('All Courses', 'All Courses'), ('React Full Stack Development', 'React Full Stack Development'), ('Software Development', 'Software Development'), ('Testing', 'Testing'), ('UI/UX Design', 'UI/UX Design'), ('Devops', 'Devops'), ('DevOps', 'DevOps'), ('AI/ML', 'AI/ML'), ('AL/ML', 'AL/ML'), ('Data Science', 'Data Science'), ('Soft Skills', 'Soft Skills')], max_length=100)),
                ('batchMonth', models.CharField(choices=[('All Batches', 'All Batches'), ('June Batch', 'June Batch'), ('Sept Batch', 'Sept Batch'), ('Dec Batch', 'Dec Batch')], max_length=100)),
                ('accessType', models.CharField(choices=[('Demo Class (Slot Booking)', 'Demo Class'), ('Full Course (Fully Paid)', 'Full Course')], default='Demo Class (Slot Booking)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('driveLink', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('targetCourse', models.CharField(choices=[('All Courses', 'All Courses'), ('React Full Stack Development', 'React Full Stack Development'), ('Software Development', 'Software Development'), ('Testing', 'Testing'), ('UI/UX Design', 'UI/UX Design'), ('Devops', 'Devops'), ('DevOps', 'DevOps'), ('AI/ML', 'AI/ML'), ('AL/ML', 'AL/ML'), ('Data Science', 'Data Science'), ('Soft Skills', 'Soft Skills')], max_length=100)),
                ('batchMonth', models.CharField(choices=[('All Batches', 'All Batches'), ('June Batch', 'June Batch'), ('Sept Batch', 'Sept Batch'), ('Dec Batch', 'Dec Batch')], max_length=100)),
                ('accessType', models.CharField(choices=[('Demo Class (Slot Booking)', 'Demo Class'), ('Full Course (Fully Paid)', 'Full Course')], default='Demo Class (Slot Booking)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(default='0000000000', max_length=15)),
                ('password', models.CharField(max_length=255)),
                ('collegeName', models.CharField(blank=True, max_length=200, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('degreeType', models.CharField(max_length=50)),
                ('passOutYear', models.CharField(max_length=10)),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('enrollmentType', models.CharField(choices=[('Training', 'Training'), ('Internship', 'Internship'), ('Training+Internship', 'Training+Internship')], default='Training', max_length=30)),
                ('courseSpecialization', models.CharField(default='Not Specified', max_length=100)),
                ('mode', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Hybrid', 'Hybrid')], default='Online', max_length=20)),
                ('couponCode', models.CharField(blank=True, max_length=50, null=True)),
                ('paymentStatus', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('items', models.JSONField()),
                ('total_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('enrollment_type', models.CharField(choices=[('full', 'Full Payment'), ('installment', 'Installment'), ('slot', 'Seat Booking')], max_length=20)),
                ('batch_date', models.CharField(max_length=50)),
                ('payment_method', models.CharField(choices=[('upi', 'UPI'), ('card', 'Card'), ('netbanking', 'Net Banking')], max_length=20)),
                ('billing_country', models.CharField(max_length=50)),
                ('billing_state', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.userregister')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(default='present', max_length=20)),
                ('course', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.student')),
            ],
            options={
                'unique_together': {('student', 'date', 'course')},
            },
        ),
    ]
