# Generated by Django 6.0.4 on 2026-04-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_liveclass_recordedclass_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('course_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=50)),
                ('img', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='liveclass',
            name='accessType',
            field=models.CharField(choices=[('Demo Class (Slot Booking)', 'Demo Class'), ('Full Course (Fully Paid)', 'Full Course')], default='Demo Class (Slot Booking)', max_length=100),
        ),
        migrations.AddField(
            model_name='recordedclass',
            name='accessType',
            field=models.CharField(choices=[('Demo Class (Slot Booking)', 'Demo Class'), ('Full Course (Fully Paid)', 'Full Course')], default='Demo Class (Slot Booking)', max_length=100),
        ),
        migrations.AddField(
            model_name='resource',
            name='accessType',
            field=models.CharField(choices=[('Demo Class (Slot Booking)', 'Demo Class'), ('Full Course (Fully Paid)', 'Full Course')], default='Demo Class (Slot Booking)', max_length=100),
        ),
        migrations.AlterField(
            model_name='liveclass',
            name='targetCourse',
            field=models.CharField(choices=[('All Courses', 'All Courses'), ('React Full Stack Development', 'React Full Stack Development'), ('Software Development', 'Software Development'), ('Testing', 'Testing'), ('UI/UX Design', 'UI/UX Design'), ('Devops', 'Devops'), ('DevOps', 'DevOps'), ('AI/ML', 'AI/ML'), ('AL/ML', 'AL/ML'), ('Data Science', 'Data Science'), ('Soft Skills', 'Soft Skills')], max_length=100),
        ),
        migrations.AlterField(
            model_name='recordedclass',
            name='targetCourse',
            field=models.CharField(choices=[('All Courses', 'All Courses'), ('React Full Stack Development', 'React Full Stack Development'), ('Software Development', 'Software Development'), ('Testing', 'Testing'), ('UI/UX Design', 'UI/UX Design'), ('Devops', 'Devops'), ('DevOps', 'DevOps'), ('AI/ML', 'AI/ML'), ('AL/ML', 'AL/ML'), ('Data Science', 'Data Science'), ('Soft Skills', 'Soft Skills')], max_length=100),
        ),
        migrations.AlterField(
            model_name='resource',
            name='targetCourse',
            field=models.CharField(choices=[('All Courses', 'All Courses'), ('React Full Stack Development', 'React Full Stack Development'), ('Software Development', 'Software Development'), ('Testing', 'Testing'), ('UI/UX Design', 'UI/UX Design'), ('Devops', 'Devops'), ('DevOps', 'DevOps'), ('AI/ML', 'AI/ML'), ('AL/ML', 'AL/ML'), ('Data Science', 'Data Science'), ('Soft Skills', 'Soft Skills')], max_length=100),
        ),
    ]
