# Generated by Django 6.0.4 on 2026-04-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_cart_liveclass_accesstype_recordedclass_accesstype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courseSpecialization',
            field=models.CharField(default='Not Specified', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='mode',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Hybrid', 'Hybrid')], default='Online', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='degreeType',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrollmentType',
            field=models.CharField(choices=[('Training', 'Training'), ('Internship', 'Internship'), ('Training+Internship', 'Training+Internship')], default='Training', max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='passOutYear',
            field=models.CharField(max_length=10),
        ),
    ]
